version: '3.7'

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
  backend:
    build: ./Backend
    ports:
     - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/docker
  frontend:
    build: ./Frontend
    ports:
     - 80:80
