# docker-compose up

version: '3.5'

services:
  backend:
    container_name: spring
    build: ./Backend
    ports:
     - 8080:8080
    depends_on:
     - database
  frontend:
    container_name: angular
    build: ./Frontend
    ports:
     - 80:80
    # depends_on:
    #  - backend
  database:
    container_name: psql
    image: postgres
    ports:
      - 5432:5432
    environment:
      #- POSTGRES_HOST=localhost
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
