version: '3.5'

services:
  backend:
    container_name: spring
    build: ./Backend
    ports:
     - 8081:8080
    depends_on:
     - database
    volumes:
     - ./Backend:/home/backend/
  frontend:
    container_name: angular
    build: ./Frontend
    ports:
     - 81:80
    volumes:
     - ./Frontend:/app
  database:
    container_name: psql
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
