# docker-compose up

version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - postgres:/data/postgres
#  backend:
#    build: .
#    ports:
#      - "8080:8080"

volumes:
  postgres:

#    networks:
#      - postgres
#
#networks:
#  postgres:
#    driver: bridge


