# docker-compose up

version: '3.5'

services:
  app:
    container_name: backend
    build: .
    ports:
      - 8081:8081
    depends_on:
      - database
  database:
    container_name: database
    image: postgres
    ports:
      - 5433:5433
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:




